name: Tableau Workbook Workflows - Production

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  tableau-production-publishing:
    name: Tableau Workbook Production Publisher
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v2

      - name: "Tableau Workbook Action - Production"
        if: github.event.pull_request.merged == true
        uses: jayamanikharyono/tableau-workbook-action@v1.3
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          SITE_ID: ${{ secrets.SITE_ID }}
          TABLEAU_URL: ${{ secrets.TABLEAU_URL }}
        with:
          workbook_dir: tableau_workbook/workbooks
          env: production
          repo_token: ${{ secrets.GITHUB_TOKEN }}
