name: Project Publisher

on:
  pull_request:
    branches:
      - main

jobs:
  scan_projects:
    name: Scan Project Files
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - name: Install yq
        run: |
          wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O yq && \
          chmod +x yq

      - name: Get changed files in the projects folder
        id: changed-files-specific
        uses: tj-actions/changed-files@v35
        with:
          files: projects/*.yml

      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files-specific.outputs.all_changed_files }}; do
            echo "$file was changed"
            yq "." $file
          done
