name: Tableau Workbook Workflows - Staging

on:
  pull_request:
    branches:
      - main

jobs:
  tableau-validation-action:
    name: Tableau Workbook Staging Publisher
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Tableau Login
        run: |
          curl --location --request POST '${{ secrets.TABLEAU_URL }}/api/3.9/auth/signin' \
          --header 'Content-Type: application/xml' \
          --data-raw '<tsRequest>
            <credentials name="${{ secrets.USERNAME }}" password="${{ secrets.PASSWORD }}">
              <site contentUrl="${{ secrets.SITE }}" />
            </credentials>
          </tsRequest>' > login.xml

          TOKEN=$(xpath -q -e "string(//@token)" login.xml)
          SITE_ID=$(xpath -q -e "string(//site/@id)" login.xml)

          echo "TOKEN=${TOKEN}" >> $GITHUB_ENV
          echo "SITE_ID=${SITE_ID}" >> $GITHUB_ENV

          echo "Login done with success"
