name: Tableau Workbook Workflows - Staging

on:
  pull_request:
    branches:
      - main

jobs:
  tableau-validation-action:
    name: Tableau Workbook Staging Publisher
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: "Tableau Workbook Action - Staging"
        uses: jayamanikharyono/tableau-workbook-action@v1.2
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          SITE_ID: ${{ secrets.SITE_ID }}
          TABLEAU_URL: ${{ secrets.TABLEAU_URL }}
        with:
          workbook_dir: tableau_workbook/workbooks
          env: staging
          repo_token: ${{ secrets.GITHUB_TOKEN }}
